<a href="https://colab.research.google.com/github/Orienfish/robust-lora/blob/emily_refactoring/pngToNp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The purpose of this program is to convert the png map prediction from GLNet result to a npy file.

In [ ]:
%pip install Pillow==6.2.2

     |████████████████████████████████| 2.1MB 4.1MB/s 
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: Pillow 7.0.0
    Uninstalling Pillow-7.0.0:
      Successfully uninstalled Pillow-7.0.0


In [ ]:

from google.colab import drive

drive.mount('/content/drive')
%cd drive/MyDrive/GLNet-master


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/GLNet-master


In [6]:
from PIL import Image 
import numpy as np

# open image in working directory
image = Image.open("./prediction/sat_test_entire_mask.png")

# convert image into np array and save as npy file
data = np.array(image)
print(data)
np.save('entire_seg_map.npy', data)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 ...

 [[255 255   0]
  [255 255   0]
  [255 255   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255 255   0]
  [255 255   0]
  [255 255   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255 255   0]
  [255 255   0]
  [255 255   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]
